global:
  scrape_interval: 15s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: DDF
    basic_auth:
      username: admin
      password: admin
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: "/metrics"
    scrape_interval: 1m
    static_configs:
      - targets: ['host.docker.internal:8993']