{
 "title": "DDF Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ddf_platform_http_latency_milliseconds_sum[5m]) / rate(ddf_platform_http_latency_milliseconds_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ddf_platform_http_latency_milliseconds_sum[5m]) / rate(ddf_platform_http_latency_milliseconds_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Latency 95th",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ddf_platform_http_latency_milliseconds{quantile=\"0.95\"}",
     "legendFormat": "{{method}} {{status}} {{quantile}}"
    }
   ]
  },
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Catalog Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ddf_catalog_query_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_query_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "query"
    },
    {
     "expr": "rate(ddf_catalog_create_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_create_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(ddf_catalog_update_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_update_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(ddf_catalog_delete_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_delete_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(ddf_catalog_resource_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_resource_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "resource"
    }
   ]
  },
  {
   "title": "Catalog Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ddf_catalog_query_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_query_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "query"
    },
    {
     "expr": "rate(ddf_catalog_create_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_create_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(ddf_catalog_update_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_update_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(ddf_catalog_delete_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_delete_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(ddf_catalog_resource_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_resource_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "resource"
    }
   ]
  },
  {
   "title": "Catalog Latency 95th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ddf_catalog_query_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "query"
    },
    {
     "expr": "ddf_catalog_create_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "create"
    },
    {
     "expr": "ddf_catalog_update_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "update"
    },
    {
     "expr": "ddf_catalog_delete_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "ddf_catalog_resource_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "resource"
    }
   ]
  },
  { "title": "Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Source Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(ddf_catalog_query_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_query_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "catalog"
    },
    {
     "expr": "rate(ddf_catalog_source_latency_milliseconds_sum[5m]) / rate(ddf_catalog_source_latency_milliseconds_count[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Source Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ddf_catalog_query_latency_milliseconds_sum{successful=\"true\"}[5m]) / rate(ddf_catalog_query_latency_milliseconds_count{successful=\"true\"}[5m])",
     "legendFormat": "catalog"
    },
    {
     "expr": "rate(ddf_catalog_source_latency_milliseconds_sum[5m]) / rate(ddf_catalog_source_latency_milliseconds_count[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Source Latency 95th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ddf_catalog_query_latency_milliseconds{quantile=\"0.95\",successful=\"true\"}",
     "legendFormat": "catalog"
    },
    {
     "expr": "ddf_catalog_source_latency_milliseconds{quantile=\"0.95\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Query Types",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ddf_catalog_query_exceptions_total[5m]))",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_comparison_total[5m]))",
     "legendFormat": "comparison"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_spatial_total[5m]))",
     "legendFormat": "spatial"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_temporal_total[5m]))",
     "legendFormat": "temporal"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_fuzzy_total[5m]))",
     "legendFormat": "fuzzy"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_function_total[5m]))",
     "legendFormat": "function"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_none_total[5m]))",
     "legendFormat": "none"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_unsupported_total[5m]))",
     "legendFormat": "unsupported"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ddf_catalog_query_exceptions_total[5m]))",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_comparison_total[5m]))",
     "legendFormat": "comparison"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_spatial_total[5m]))",
     "legendFormat": "spatial"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_temporal_total[5m]))",
     "legendFormat": "temporal"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_fuzzy_total[5m]))",
     "legendFormat": "fuzzy"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_function_total[5m]))",
     "legendFormat": "function"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_none_total[5m]))",
     "legendFormat": "none"
    },
    {
     "expr": "sum(rate(ddf_catalog_query_unsupported_total[5m]))",
     "legendFormat": "unsupported"
    }
   ]
  },
  {
   "title": "Query Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ddf_catalog_query_exceptions_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}